package api

import (
	"github.com/go-chi/chi/v5"
)

// Handler returns an instance of chi.Router that handles APIs registered here
func (rt *_router) Handler() chi.Router {
	// Register routes
	rt.router.Get("/", rt.getHelloWorld)
	rt.router.Get("/context", rt.wrap(rt.getContextReply))
	rt.router.Get("/t", rt.ticketValidationPage)
	rt.router.Get("/tickets/validate", rt.wrap(rt.ticketValidationStatus))

	// Special routes
	rt.router.Get("/liveness", rt.liveness)

	rt.router.Post("/vote", rt.wrap(rt.postVote))
	// Admin CRUD routes
	rt.router.Post("/admin/login", rt.wrap(rt.adminLogin))

	rt.router.Get("/public/players", rt.wrap(rt.listPublicPlayers))
	rt.router.Get("/shop/products", rt.wrap(rt.listShopProducts))
	rt.router.Get("/shop/products/{id}", rt.wrap(rt.getShopProduct))
	rt.router.Post("/shop/checkout", rt.wrap(rt.checkoutShopOrder))
	rt.router.Get("/bar/categories", rt.wrap(rt.listBarCategories))
	rt.router.Get("/bar/products", rt.wrap(rt.listBarProducts))
	rt.router.Get("/bar/suggestions/{productID}", rt.wrap(rt.getBarSuggestions))
	rt.router.Post("/ai/bar/upsell", rt.wrap(rt.generateAIUpsellSuggestions))
	rt.router.Post("/ai/popups/generate", rt.wrap(rt.generateAIPopupMessage))
	rt.router.Post("/ai/interactions/{id}/track", rt.wrap(rt.trackAIInteractionOutcome))
	rt.router.Post("/bar/checkout/session", rt.wrap(rt.createBarCheckoutSession))
	rt.router.Post("/bar/checkout/confirm", rt.wrap(rt.confirmBarCheckoutSession))
	rt.router.Post("/bar/stripe/webhook", rt.wrap(rt.handleBarStripeWebhook))
	rt.router.Get("/admin/shop/products", rt.wrapAdmin(rt.listAdminShopProducts))
	rt.router.Post("/admin/shop/products", rt.wrapAdmin(rt.createAdminShopProduct))
	rt.router.Get("/admin/shop/orders", rt.wrapAdmin(rt.listAdminShopOrders))

	rt.router.Get("/teams", rt.wrapAdmin(rt.listTeams))
	rt.router.Post("/teams", rt.wrapAdmin(rt.createTeam))
	rt.router.Put("/teams/{id}", rt.wrapAdmin(rt.updateTeam))
	rt.router.Delete("/teams/{id}", rt.wrapAdmin(rt.deleteTeam))

	rt.router.Get("/players", rt.wrapAdmin(rt.listPlayers))
	rt.router.Post("/players", rt.wrapAdmin(rt.createPlayer))
	rt.router.Put("/players/settings", rt.wrapAdmin(rt.updatePlayerSettings))
	rt.router.Put("/players/{id}", rt.wrapAdmin(rt.updatePlayer))
	rt.router.Delete("/players/{id}", rt.wrapAdmin(rt.deletePlayer))

	rt.router.Get("/active-event", rt.wrap(rt.getActiveEvent))
	rt.router.Get("/sponsors", rt.wrap(rt.listPublicSponsors))
	rt.router.Get("/events/{eventId}/coupons", rt.wrap(rt.listEventCoupons))
	rt.router.Post("/coupons/{couponId}/view", rt.wrap(rt.recordCouponView))
	rt.router.Post("/coupons/{couponId}/claim", rt.wrap(rt.claimCoupon))
	rt.router.Get("/user/coupons", rt.wrap(rt.listUserCoupons))
	rt.router.Post("/partner/login", rt.wrap(rt.partnerLogin))
	rt.router.Post("/partner/coupons/validate", rt.wrapPartner(rt.validatePartnerCoupon))
	rt.router.Post("/auth/start", rt.wrap(rt.postAuthStart))
	rt.router.Post("/auth/verify", rt.wrap(rt.postAuthVerify))
	rt.router.Post("/auth/resend", rt.wrap(rt.postAuthResend))

	rt.router.Post("/events/{eventId}/engagement", rt.wrap(rt.recordPageEngagement))
	rt.router.Post("/events/{eventId}/tracking/events", rt.wrap(rt.recordTrackingEvents))
	rt.router.Get("/events/{eventId}/engagement", rt.wrap(rt.getEventEngagementStats))
	rt.router.Post("/events/{eventId}/sponsors/session", rt.wrap(rt.recordSponsorSessionEvent))
	rt.router.Post("/events/{eventId}/sponsors/exposures", rt.wrap(rt.recordSponsorExposureEvent))
	rt.router.Post("/events/{eventId}/sponsors/{sponsorId}/click", rt.wrap(rt.recordSponsorClick))
	rt.router.Post("/events/{eventId}/post-vote-actions", rt.wrap(rt.recordPostVoteAction))
	rt.router.Get("/events/{eventId}/contacts", rt.wrap(rt.listContactBonuses))
	rt.router.Post("/events/{eventId}/contacts", rt.wrap(rt.submitContact))

	rt.router.Post("/fan/register", rt.wrap(rt.postRegisterFan))
	rt.router.Get("/fan/me", rt.wrap(rt.getFanMe))
	rt.router.Put("/fan/nickname", rt.wrap(rt.putFanNickname))
	rt.router.Post("/events/{eventId}/guest-coins", rt.wrap(rt.postGuestCoins))
	rt.router.Get("/events/{eventId}/coins-leaderboard", rt.wrap(rt.getCoinsLeaderboard))
	rt.router.Post("/events/{eventId}/rewards/redeem", rt.wrap(rt.postFanRewardRedeem))
	rt.router.Get("/events/{eventId}/tap-live/stream", rt.wrap(rt.getTapLiveStream))
	rt.router.Post("/events/{eventId}/tap-live/queue", rt.wrap(rt.postTapLiveQueue))
	rt.router.Delete("/events/{eventId}/tap-live/queue", rt.wrap(rt.deleteTapLiveQueue))
	rt.router.Get("/events/{eventId}/tap-live/state", rt.wrap(rt.getTapLiveState))
	rt.router.Post("/events/{eventId}/tap-live/submit", rt.wrap(rt.postTapLiveSubmit))
	rt.router.Post("/events/{eventId}/tap-live/abort", rt.wrap(rt.postTapLiveAbort))
	rt.router.Get("/events/{eventId}/tap-live/result", rt.wrap(rt.getTapLiveResult))
	rt.router.Post("/events/{eventId}/tap-live/rematch", rt.wrap(rt.postTapLiveRematch))
	rt.router.Post("/events/{eventId}/tap-live/postmatch-leave", rt.wrap(rt.postTapLivePostmatchLeave))

	rt.router.Get("/events", rt.wrapAdmin(rt.listEvents))
	rt.router.Post("/events", rt.wrapAdmin(rt.createEvent))
	rt.router.Post("/events/deactivate", rt.wrapAdmin(rt.deactivateEvents))
	rt.router.Post("/events/{id}/close-votes", rt.wrapAdmin(rt.closeEventVoting))
	rt.router.Post("/events/{id}/conclude", rt.wrapAdmin(rt.concludeEvent))
	rt.router.Post("/events/{id}/activate", rt.wrapAdmin(rt.activateEvent))
	rt.router.Put("/events/{id}", rt.wrapAdmin(rt.updateEvent))
	rt.router.Delete("/events/{id}", rt.wrapAdmin(rt.deleteEvent))
	rt.router.Get("/events/{id}/tickets", rt.wrapAdmin(rt.listEventTickets))
	rt.router.Post("/events/{id}/validate-ticket", rt.wrapAdmin(rt.validateTicket))
	rt.router.Post("/events/{eventId}/prizes/{prizeId}/assign", rt.wrapAdmin(rt.assignPrizeWinner))
	rt.router.Post("/notifications/test-sms", rt.wrapAdmin(rt.sendTestWinnerSMS))
	rt.router.Delete("/events/{eventId}/prizes/{prizeId}/winner", rt.wrapAdmin(rt.clearPrizeWinner))
	rt.router.Get("/events/{id}/results", rt.wrap(rt.getEventResults))
	rt.router.Get("/events/{id}/votes/count", rt.wrap(rt.getEventVoteCount))
	rt.router.Get("/events/{id}/votes/live", rt.wrap(rt.getLiveEventVotes))
	rt.router.Get("/events/{id}/votes/stream", rt.wrap(rt.getVotesStream))
	rt.router.Get("/events/{eventId}/coins/stream", rt.wrap(rt.getCoinsStream))
	rt.router.Get("/events/{id}/vote-status", rt.wrap(rt.getVoteStatus))
	rt.router.Get("/events/{eventId}/stories", rt.wrap(rt.listPublicEventStories))
	rt.router.Get("/events/{eventId}/stories/videos/{filename}", rt.wrap(rt.getEventStoryVideo))
	rt.router.Post("/events/{eventId}/selfies", rt.wrap(rt.postSelfie))
	rt.router.Get("/events/{eventId}/selfies/me", rt.wrap(rt.getOwnSelfie))
	rt.router.Get("/events/{eventId}/selfies/approved", rt.wrap(rt.listApprovedSelfies))
	rt.router.Get("/events/{eventId}/selfies/{selfieId}/image", rt.wrap(rt.getSelfieImage))
	rt.router.Get("/events/{eventId}/reaction-test", rt.wrap(rt.getReactionTestStatus))
	rt.router.Post("/events/{eventId}/reaction-test", rt.wrap(rt.postReactionTestResult))
	rt.router.Get("/public/events/{eventId}/quiz", rt.wrap(rt.getPublicEventQuiz))
	rt.router.Post("/public/events/{eventId}/quiz/answer", rt.wrap(rt.postPublicEventQuizAnswer))
	rt.router.Post("/events/{eventId}/feedback", rt.wrap(rt.submitEventFeedback))
	rt.router.Get("/admin/events/history", rt.wrapAdmin(rt.getEventHistory))
	rt.router.Get("/admin/events/history/{eventId}/report", rt.wrapAdmin(rt.downloadEventHistoryReport))
	rt.router.Get("/admin/events/{eventId}/ai-report", rt.wrapAdmin(rt.getAdminEventAIReport))
	rt.router.Post("/admin/events/{eventId}/ai-report", rt.wrapAdmin(rt.generateAdminEventAIReport))
	rt.router.Get("/admin/events/{eventId}/sponsors/analytics", rt.wrapAdmin(rt.getSponsorAnalytics))
	rt.router.Post("/admin/events/{id}/purge", rt.wrapAdmin(rt.purgeEvent))
	rt.router.Get("/admin/events/{eventId}/selfies", rt.wrapAdmin(rt.listAdminSelfies))
	rt.router.Get("/admin/events/{eventId}/quiz", rt.wrapAdmin(rt.getAdminEventQuiz))
	rt.router.Put("/admin/events/{eventId}/quiz", rt.wrapAdmin(rt.putAdminEventQuiz))
	rt.router.Get("/admin/events/{eventId}/quiz/questions", rt.wrapAdmin(rt.getAdminEventQuizQuestions))
	rt.router.Post("/admin/events/{eventId}/quiz/questions", rt.wrapAdmin(rt.postAdminEventQuizQuestion))
	rt.router.Put("/admin/events/{eventId}/quiz/questions/{id}", rt.wrapAdmin(rt.putAdminEventQuizQuestion))
	rt.router.Delete("/admin/events/{eventId}/quiz/questions/{id}", rt.wrapAdmin(rt.deleteAdminEventQuizQuestion))
	rt.router.Get("/admin/events/{eventId}/stories", rt.wrapAdmin(rt.listAdminEventStories))
	rt.router.Post("/admin/events/{eventId}/stories", rt.wrapAdmin(rt.createAdminEventStory))
	rt.router.Post("/admin/events/{eventId}/stories/upload-video", rt.wrapAdmin(rt.uploadAdminStoryVideo))
	rt.router.Put("/admin/events/{eventId}/stories/{storyId}", rt.wrapAdmin(rt.updateAdminEventStory))
	rt.router.Delete("/admin/events/{eventId}/stories/{storyId}", rt.wrapAdmin(rt.deleteAdminEventStory))
	rt.router.Put("/admin/selfies/{selfieId}", rt.wrapAdmin(rt.updateSelfieModeration))
	rt.router.Delete("/admin/selfies/{selfieId}", rt.wrapAdmin(rt.deleteSelfie))
	rt.router.Get("/admin/selfies/{selfieId}/image", rt.wrapAdmin(rt.getAdminSelfieImage))

	rt.router.Get("/votes", rt.wrapAdmin(rt.listVotes))
	rt.router.Delete("/votes/{id}", rt.wrapAdmin(rt.deleteVote))

	rt.router.Get("/admins", rt.wrapAdmin(rt.listAdmins))
	rt.router.Post("/admins", rt.wrapAdmin(rt.createAdmin))
	rt.router.Put("/admins/{id}", rt.wrapAdmin(rt.updateAdmin))
	rt.router.Delete("/admins/{id}", rt.wrapAdmin(rt.deleteAdmin))
	rt.router.Get("/admin/partners", rt.wrapAdmin(rt.listPartners))
	rt.router.Post("/admin/partners", rt.wrapAdmin(rt.createPartner))
	rt.router.Put("/admin/partners/{id}", rt.wrapAdmin(rt.updatePartner))
	rt.router.Delete("/admin/partners/{id}", rt.wrapAdmin(rt.deletePartner))
	rt.router.Get("/admin/bar/overview", rt.wrapAdmin(rt.getAdminBarOverview))
	rt.router.Get("/admin/bar/categories", rt.wrapAdmin(rt.listAdminBarCategories))
	rt.router.Post("/admin/bar/categories", rt.wrapAdmin(rt.createAdminBarCategory))
	rt.router.Put("/admin/bar/categories/{id}", rt.wrapAdmin(rt.updateAdminBarCategory))
	rt.router.Delete("/admin/bar/categories/{id}", rt.wrapAdmin(rt.deleteAdminBarCategory))
	rt.router.Get("/admin/bar/products", rt.wrapAdmin(rt.listAdminBarProducts))
	rt.router.Post("/admin/bar/products", rt.wrapAdmin(rt.createAdminBarProduct))
	rt.router.Get("/admin/bar/suggestions/products", rt.wrapAdmin(rt.listAdminBarProductSuggestions))
	rt.router.Put("/admin/bar/suggestions/products/{productID}", rt.wrapAdmin(rt.upsertAdminBarProductSuggestions))
	rt.router.Get("/admin/bar/suggestions/categories", rt.wrapAdmin(rt.listAdminBarCategorySuggestions))
	rt.router.Put("/admin/bar/suggestions/categories/{categoryID}", rt.wrapAdmin(rt.upsertAdminBarCategorySuggestions))
	rt.router.Delete("/admin/bar/products/{id}", rt.wrapAdmin(rt.deleteAdminBarProduct))
	rt.router.Get("/admin/bar/menus", rt.wrapAdmin(rt.listAdminBarMenus))
	rt.router.Post("/admin/bar/menus", rt.wrapAdmin(rt.createAdminBarMenu))
	rt.router.Delete("/admin/bar/menus/{id}", rt.wrapAdmin(rt.deleteAdminBarMenu))
	rt.router.Get("/admin/bar/orders", rt.wrapAdmin(rt.listAdminBarOrders))
	rt.router.Get("/admin/bar/orders/stream", rt.wrapAdmin(rt.streamAdminBarOrders))
	rt.router.Put("/admin/bar/orders/{id}/status", rt.wrapAdmin(rt.updateAdminBarOrderStatus))
	rt.router.Get("/admin/master/summary", rt.wrapAdmin(rt.getMasterSummary))
	rt.router.Get("/admin/master/analytics", rt.wrapAdmin(rt.getMasterAnalytics))
	rt.router.Get("/admin/master/organizations", rt.wrapAdmin(rt.listMasterOrganizations))
	rt.router.Post("/admin/master/organizations", rt.wrapAdmin(rt.createMasterOrganization))
	rt.router.Get("/admin/master/organizations/{id}", rt.wrapAdmin(rt.getMasterOrganizationDetail))
	rt.router.Put("/admin/master/organizations/{id}", rt.wrapAdmin(rt.updateMasterOrganization))
	rt.router.Get("/admin/master/qr-redirects", rt.wrapAdmin(rt.listMasterQRRedirects))
	rt.router.Post("/admin/master/qr-redirects", rt.wrapAdmin(rt.upsertMasterQRRedirect))
	rt.router.Delete("/admin/master/qr-redirects/{id}", rt.wrapAdmin(rt.deleteMasterQRRedirect))

	rt.router.Get("/admin/sponsors", rt.wrapAdmin(rt.listAllSponsors))
	rt.router.Post("/admin/sponsors", rt.wrapAdmin(rt.createSponsor))
	rt.router.Put("/admin/sponsors/{id}", rt.wrapAdmin(rt.updateSponsor))
	rt.router.Delete("/admin/sponsors/{id}", rt.wrapAdmin(rt.deleteSponsor))

	rt.router.Get("/admin/marketing/audience", rt.wrapAdmin(rt.listMarketingAudience))
	rt.router.Get("/admin/marketing/audience/{fanId}", rt.wrapAdmin(rt.getMarketingAudienceFan))
	rt.router.Post("/admin/marketing/sms/single", rt.wrapAdmin(rt.sendSingleMarketingSMS))
	rt.router.Get("/admin/marketing/campaigns", rt.wrapAdmin(rt.listSMSCampaigns))
	rt.router.Post("/admin/marketing/campaigns", rt.wrapAdmin(rt.createSMSCampaign))
	rt.router.Post("/admin/marketing/campaigns/{id}/test", rt.wrapAdmin(rt.sendSMSCampaignTest))
	rt.router.Post("/admin/marketing/campaigns/{id}/send-now", rt.wrapAdmin(rt.sendSMSCampaignNow))
	rt.router.Get("/admin/marketing/templates", rt.wrapAdmin(rt.listSMSTemplates))
	rt.router.Post("/admin/marketing/templates", rt.wrapAdmin(rt.createSMSTemplate))
	rt.router.Put("/admin/marketing/templates/{id}", rt.wrapAdmin(rt.updateSMSTemplate))
	rt.router.Delete("/admin/marketing/templates/{id}", rt.wrapAdmin(rt.deleteSMSTemplate))
	rt.router.Get("/admin/marketing/logs", rt.wrapAdmin(rt.listSMSLogs))
	rt.router.Get("/admin/marketing/billing", rt.wrapAdmin(rt.getSMSBillingSummary))
	rt.router.Get("/admin/coupons", rt.wrapAdmin(rt.listAdminCoupons))
	rt.router.Post("/admin/coupons", rt.wrapAdmin(rt.createAdminCoupon))
	rt.router.Put("/admin/coupons/{id}", rt.wrapAdmin(rt.updateAdminCoupon))
	rt.router.Delete("/admin/coupons/{id}", rt.wrapAdmin(rt.deleteAdminCoupon))

	rt.router.NotFound(rt.wrap(rt.handleQRRedirectNotFound))

	return rt.router
}
